services:
  leitor-folha-processos:
    image: leitor-folha-processos
    networks:
      - proxy
      - database

networks:
  proxy:
    external: true
    name: server-infra-prod_proxy
  database:
    external: true
    name: server-infra-prod_database
