services:
  leitor-folha-processos:
    image: leitor-folha-processos-dev
    networks:
      - proxy
      - database

networks:
  proxy:
    external: true
    name: server-infra-dev_proxy
  database:
    external: true
    name: server-infra-dev_database
